const MEDICATIONS = [
  { displayName: 'Alfuzosin', name: 'alfuzosin' },
  { displayName: 'Amiodarone', name: 'amiodarone' },
  { displayName: 'Amlodipine', name: 'amlodipine' },
  { displayName: 'Amprenavir', name: 'amprenavir' },
  { displayName: 'Apalutamide', name: 'apalutamide' },
  { displayName: 'Atazanavir', name: 'atazanavir' },
  { displayName: 'Atorvastatin', name: 'atorvastatin' },
  { displayName: 'Bedaquiline', name: 'bedaquiline' },
  { displayName: 'Bepridil', name: 'bepridil' },
  { displayName: 'Betamethasone', name: 'betamethasone' },
  { displayName: 'Bictegravir', name: 'bictegravir' },
  { displayName: 'Bosentan', name: 'bosentan' },
  { displayName: 'Budesonide', name: 'budesonide' },
  { displayName: 'Bupropion', name: 'bupropion' },
  { displayName: 'Carbamazepine', name: 'carbamazepine' },
  { displayName: 'Chloroquine phosphate', name: 'chloroquine_phosphate' },
  { displayName: 'Ciclesonide', name: 'ciclesonide' },
  { displayName: 'Clarithromycin', name: 'clarithromycin' },
  { displayName: 'Clozapine', name: 'clozapine' },
  { displayName: 'Colchicine', name: 'colchicine' },
  { displayName: 'Cyclosporine', name: 'cyclosporine' },
  { displayName: 'Darunavir', name: 'darunavir' },
  { displayName: 'Dasabuvir', name: 'dasabuvir' },
  { displayName: 'Delavirdine', name: 'delavirdine' },
  { displayName: 'Dexamethasone', name: 'dexamethasone' },
  { displayName: 'Didanosine', name: 'didanosine' },
  { displayName: 'Digoxin', name: 'digoxin' },
  { displayName: 'Dihydroergotamine', name: 'dihydroergotamine' },
  { displayName: 'Diltiazem', name: 'diltiazem' },
  { displayName: 'Dronedarone', name: 'dronedarone' },
  { displayName: 'Efavirenz', name: 'efavirenz' },
  { displayName: 'Elbasvir', name: 'elbasvir' },
  { displayName: 'Emtricitabine', name: 'emtricitabine' },
  { displayName: 'Encorafenib', name: 'encorafenib' },
  { displayName: 'Ergotamine', name: 'ergotamine' },
  { displayName: 'Erythromycin', name: 'erythromycin' },
  { displayName: 'Ethinyl estradiol', name: 'ethinyl_estradiol' },
  { displayName: 'Felodipine', name: 'felodipine' },
  { displayName: 'Fentanyl', name: 'fentanyl' },
  { displayName: 'Flecainide', name: 'flecainide' },
  { displayName: 'Fluticasone', name: 'fluticasone' },
  { displayName: 'Fosamprenavir', name: 'fosamprenavir' },
  { displayName: 'Glecaprevir', name: 'glecaprevir' },
  { displayName: 'Grazoprevir', name: 'grazoprevir' },
  { displayName: 'HIV Infection (untreated)', name: 'hiv_infection' },
  { displayName: 'Hydroxychloroquine sulfate', name: 'hydroxychloroquine_sulfate' },
  { displayName: 'Ibrutinib', name: 'ibrutinib' },
  { displayName: 'Indinavir', name: 'indinavir' },
  { displayName: 'Isavuconazonium sulfate', name: 'isavuconazonium_sulfate' },
  { displayName: 'Itraconazole', name: 'itraconazole' },
  { displayName: 'Ivosidenib', name: 'ivosidenib' },
  { displayName: 'Ketoconazole', name: 'ketoconazole' },
  { displayName: 'Lidocaine (systemic)', name: 'lidocaine_systemic' },
  { displayName: 'Lovastatin', name: 'lovastatin' },
  { displayName: 'Low oxygen or needing to use an oxygen tank', name: 'low_oxygen' },
  { displayName: 'Lurasidone', name: 'lurasidone' },
  { displayName: 'Maraviroc', name: 'maraviroc' },
  { displayName: 'Methadone', name: 'methadone' },
  { displayName: 'Methylergonovine', name: 'methylergonovine' },
  { displayName: 'Methylprednisolone', name: 'methylprednisolone' },
  { displayName: 'Midazolam (not oral)', name: 'midazolam_not_oral' },
  { displayName: 'Midazolam (oral)', name: 'midazolam_oral' },
  { displayName: 'Mometasone', name: 'mometasone' },
  { displayName: 'Nelfinavir', name: 'nelfinavir' },
  { displayName: 'Neratinib', name: 'neratinib' },
  { displayName: 'Nevirapine', name: 'nevirapine' },
  { displayName: 'Nicardipine', name: 'nicardipine' },
  { displayName: 'Nifedipine', name: 'nifedipine' },
  { displayName: 'Ombitasvir', name: 'ombitasvir' },
  { displayName: 'Paritaprevir', name: 'paritaprevir' },
  { displayName: 'Pethidine', name: 'pethidine' },
  { displayName: 'Phenobarbital', name: 'phenobarbital' },
  { displayName: 'Phenytoin', name: 'phenytoin' },
  { displayName: 'Pibrentasvir', name: 'pibrentasvir' },
  { displayName: 'Pimozide', name: 'pimozide' },
  { displayName: 'Piroxicam', name: 'piroxicam' },
  { displayName: 'Prednisone', name: 'prednisone' },
  { displayName: 'Propafenone', name: 'propafenone' },
  { displayName: 'Propoxyphene', name: 'propoxyphene' },
  { displayName: 'Quetiapine', name: 'quetiapine' },
  { displayName: 'Quinidine', name: 'quinidine' },
  { displayName: 'Raltegravir', name: 'raltegravir' },
  { displayName: 'Ranolazine', name: 'ranolazine' },
  { displayName: 'Rifabutin', name: 'rifabutin' },
  { displayName: 'Rifampin (rifampicin)', name: 'rifampin' },
  { displayName: 'Rivaroxaban', name: 'rivaroxaban' },
  { displayName: 'Rosuvastatin', name: 'rosuvastatin' },
  { displayName: 'Salmeterol', name: 'salmeterol' },
  { displayName: 'Saquinavir', name: 'saquinavir' },
  { displayName: 'Sildenafil (pulmonary arterial hypertension use)', name: 'sildenafil' },
  { displayName: 'Simvastatin', name: 'simvastatin' },
  { displayName: 'Sirolimus', name: 'sirolimus' },
  { displayName: 'Sofosbuvir', name: 'sofosbuvir' },
  { displayName: "St. John's Wort", name: 'st_Johns_wort' },
  { displayName: 'Tacrolimus', name: 'tacrolimus' },
  { displayName: 'Tenofovir', name: 'tenofovir' },
  { displayName: 'Tipranavir', name: 'tipranavir' },
  { displayName: 'Trazodone', name: 'trazodone' },
  { displayName: 'Triamcinolone', name: 'triamcinolone' },
  { displayName: 'Triazolam', name: 'triazolam' },
  { displayName: 'Velpatasvir', name: 'velpatasvir' },
  { displayName: 'Venetoclax', name: 'venetoclax' },
  { displayName: 'Vinblastine', name: 'vinblastine' },
  { displayName: 'Vincristine', name: 'vincristine' },
  { displayName: 'Voriconazole', name: 'voriconazole' },
  { displayName: 'Voxilaprevir', name: 'voxilaprevir' },
  { displayName: 'Warfarin', name: 'warfarin' },
  { displayName: 'Zidovudine', name: 'zidovudine' },
  // { displayName: 'None of the medications listed', name: 'none_of_the_medications_listed' },
];

const NONE_OF_THE_ABOVE = 'none_of_the_above';

const SYMPTOMS = [
  { displayName: 'Sore throat', name: 'sore_throat' },
  { displayName: 'Runny nose', name: 'runny_nose' },
  { displayName: 'Fever greater than 100.4 F / 38 C', name: 'fever_greater_than_1004' },
  { displayName: 'Sinus congestion', name: 'sinus_congestion' },
  { displayName: 'Coughing', name: 'coughing' },
  { displayName: 'Shortness of breath', name: 'shortness_of_breath' },
  { displayName: 'Nausea', name: 'nausea' },
  { displayName: 'Headache', name: 'headache' },
  { displayName: 'Diarrhea', name: 'diarrhea' },
  { displayName: 'New onset fatigue', name: 'new_onset_fatigue' },
  { displayName: 'Swollen lymph nodes in your neck', name: 'swollen_lymph_nodes_in_your_neck' },
  { displayName: 'White or red spots on tonsils', name: 'white_spots_on_tonsils' },
  { displayName: 'Wheezing', name: 'wheezing' },
  { displayName: 'Bloody nasal discharge', name: 'bloody_nasal_discharge' },
  { displayName: 'Sinus tenderness', name: 'sinus_tenderness' },
  { displayName: 'Other', name: 'other' },
  { displayName: 'None of the above', name: 'none_of_the_above' },
];

const DISEASES = [
  { displayName: 'Untreated coronary artery disease', name: 'untreated_coronary_artery_disease' },
  {
    displayName: 'Heart attack or stroke within the last six months',
    name: 'heart_attack_or_stroke_within_the_last_six_months',
  },
  {
    displayName: 'Pregnant, or trying to get pregnant',
    name: 'pregnant_or_trying_to_get_pregnant',
  },
  { displayName: 'Breast-feeding', name: 'breast_feeding' },
  { displayName: 'Kidney disease', name: 'kidney_disease' },
  { displayName: 'Liver disease', name: 'liver_disease' },
];

const EXPOSED_DIAGNOSIS = [
  { displayName: 'Influenza (flu)', name: 'influenza' },
  { displayName: 'Strep throat', name: 'strep_throat' },
  { displayName: 'RSV', name: 'rsv' },
  { displayName: 'COVID-19', name: 'covid_19' },
  { displayName: 'Not sure', name: 'unsure' },
  { displayName: 'None of the above', name: 'none_of_the_above' },
];

const SERIOUS_SYMPTOMS = [
  { displayName: 'Trouble breathing', description: 'Difficulty breathing, faster breathing' },
  { displayName: 'Have had a seizure', description: 'In the last <5 years>' },
  { displayName: 'Feeling disoriented or confused', description: 'Including mood changes' },
  { displayName: 'Can’t keep liquids down', description: 'Continuous vomiting' },
  { displayName: 'Can’t swallow liquids', description: 'Throat is too tight' },
  { displayName: 'None of the above' },
];

const APPLY_CONDITIONS = [
  { displayName: 'This evaluation is for someone under 3 years of age' },
  { displayName: 'I have a fever less than 100.4 F / 38 C' },
  { displayName: 'I’ve had a stroke in the last 6 months' },
  { displayName: 'I am pregnant or nursing' },
  { displayName: 'None of the above' },
];

export {
  SYMPTOMS,
  DISEASES,
  EXPOSED_DIAGNOSIS,
  SERIOUS_SYMPTOMS,
  APPLY_CONDITIONS,
  NONE_OF_THE_ABOVE,
};

export default MEDICATIONS;
