const SYMPTOM_NONE = { displayName: 'None of the Above', name: 'none_of_the_above' };

const SYMPTOMS = [
  { displayName: 'Congestion or runny nose', name: 'congestion_or_runny_nose' },
  { displayName: 'Cough', name: 'cough' },
  { displayName: 'Diarrhea', name: 'diarrhea' },
  { displayName: 'Fatigue', name: 'fatigue' },
  { displayName: 'Fever over 100.4F/38C or chills', name: 'fever_or_chills' },
  { displayName: 'Headache', name: 'headache' },
  { displayName: 'Muscle or body aches', name: 'muscle_or_body_aches' },
  { displayName: 'Nausea/Vomiting', name: 'nausea_vomiting' },
  { displayName: 'New loss of taste or smell', name: 'loss_of_taste_or_smell' },
  { displayName: 'Shortness of breath or difficulty breathing', name: 'shortness_of_breath' },
  { displayName: 'Sore throat', name: 'sore_throat' },
  SYMPTOM_NONE,
];

const MEDICATIONS = [
  { displayName: 'Alfuzosin', name: 'alfuzosin' },
  { displayName: 'Amiodarone', name: 'amiodarone' },
  { displayName: 'Amlodipine', name: 'amlodipine' },
  { displayName: 'Amprenavir', name: 'amprenavir' },
  { displayName: 'Apalutamide', name: 'apalutamide' },
  { displayName: 'Atazanavir', name: 'atazanavir' },
  { displayName: 'Atorvastatin', name: 'atorvastatin' },
  { displayName: 'Bedaquiline', name: 'bedaquiline' },
  { displayName: 'Bepridil', name: 'bepridil' },
  { displayName: 'Betamethasone', name: 'betamethasone' },
  { displayName: 'Bictegravir', name: 'bictegravir' },
  { displayName: 'Bosentan', name: 'bosentan' },
  { displayName: 'Budesonide', name: 'budesonide' },
  { displayName: 'Bupropion', name: 'bupropion' },
  { displayName: 'Carbamazepine', name: 'carbamazepine' },
  { displayName: 'Chloroquine phosphate', name: 'chloroquine_phosphate' },
  { displayName: 'Ciclesonide', name: 'ciclesonide' },
  { displayName: 'Clarithromycin', name: 'clarithromycin' },
  { displayName: 'Clozapine', name: 'clozapine' },
  { displayName: 'Colchicine', name: 'colchicine' },
  { displayName: 'Cyclosporine', name: 'cyclosporine' },
  { displayName: 'Darunavir', name: 'darunavir' },
  { displayName: 'Dasabuvir', name: 'dasabuvir' },
  { displayName: 'Delavirdine', name: 'delavirdine' },
  { displayName: 'Dexamethasone', name: 'dexamethasone' },
  { displayName: 'Didanosine', name: 'didanosine' },
  { displayName: 'Digoxin', name: 'digoxin' },
  { displayName: 'Dihydroergotamine', name: 'dihydroergotamine' },
  { displayName: 'Diltiazem', name: 'diltiazem' },
  { displayName: 'Dronedarone', name: 'dronedarone' },
  { displayName: 'Efavirenz', name: 'efavirenz' },
  { displayName: 'Elbasvir', name: 'elbasvir' },
  { displayName: 'Emtricitabine', name: 'emtricitabine' },
  { displayName: 'Encorafenib', name: 'encorafenib' },
  { displayName: 'Ergotamine', name: 'ergotamine' },
  { displayName: 'Erythromycin', name: 'erythromycin' },
  { displayName: 'Ethinyl estradiol', name: 'ethinyl_estradiol' },
  { displayName: 'Felodipine', name: 'felodipine' },
  { displayName: 'Fentanyl', name: 'fentanyl' },
  { displayName: 'Flecainide', name: 'flecainide' },
  { displayName: 'Fluticasone', name: 'fluticasone' },
  { displayName: 'Fosamprenavir', name: 'fosamprenavir' },
  { displayName: 'Glecaprevir', name: 'glecaprevir' },
  { displayName: 'Grazoprevir', name: 'grazoprevir' },
  { displayName: 'HIV Infection (untreated)', name: 'hiv_infection' },
  { displayName: 'Hydroxychloroquine sulfate', name: 'hydroxychloroquine_sulfate' },
  { displayName: 'Ibrutinib', name: 'ibrutinib' },
  { displayName: 'Indinavir', name: 'indinavir' },
  { displayName: 'Isavuconazonium sulfate', name: 'isavuconazonium_sulfate' },
  { displayName: 'Itraconazole', name: 'itraconazole' },
  { displayName: 'Ivosidenib', name: 'ivosidenib' },
  { displayName: 'Ketoconazole', name: 'ketoconazole' },
  { displayName: 'Lidocaine (systemic)', name: 'lidocaine_systemic' },
  { displayName: 'Lovastatin', name: 'lovastatin' },
  { displayName: 'Low oxygen or needing to use an oxygen tank', name: 'low_oxygen' },
  { displayName: 'Lurasidone', name: 'lurasidone' },
  { displayName: 'Maraviroc', name: 'maraviroc' },
  { displayName: 'Methadone', name: 'methadone' },
  { displayName: 'Methylergonovine', name: 'methylergonovine' },
  { displayName: 'Methylprednisolone', name: 'methylprednisolone' },
  { displayName: 'Midazolam (not oral)', name: 'midazolam_not_oral' },
  { displayName: 'Midazolam (oral)', name: 'midazolam_oral' },
  { displayName: 'Mometasone', name: 'mometasone' },
  { displayName: 'Nelfinavir', name: 'nelfinavir' },
  { displayName: 'Neratinib', name: 'neratinib' },
  { displayName: 'Nevirapine', name: 'nevirapine' },
  { displayName: 'Nicardipine', name: 'nicardipine' },
  { displayName: 'Nifedipine', name: 'nifedipine' },
  { displayName: 'Ombitasvir', name: 'ombitasvir' },
  { displayName: 'Paritaprevir', name: 'paritaprevir' },
  { displayName: 'Pethidine', name: 'pethidine' },
  { displayName: 'Phenobarbital', name: 'phenobarbital' },
  { displayName: 'Phenytoin', name: 'phenytoin' },
  { displayName: 'Pibrentasvir', name: 'pibrentasvir' },
  { displayName: 'Pimozide', name: 'pimozide' },
  { displayName: 'Piroxicam', name: 'piroxicam' },
  { displayName: 'Prednisone', name: 'prednisone' },
  { displayName: 'Propafenone', name: 'propafenone' },
  { displayName: 'Propoxyphene', name: 'propoxyphene' },
  { displayName: 'Quetiapine', name: 'quetiapine' },
  { displayName: 'Quinidine', name: 'quinidine' },
  { displayName: 'Raltegravir', name: 'raltegravir' },
  { displayName: 'Ranolazine', name: 'ranolazine' },
  { displayName: 'Rifabutin', name: 'rifabutin' },
  { displayName: 'Rifampin (rifampicin)', name: 'rifampin' },
  { displayName: 'Rivaroxaban', name: 'rivaroxaban' },
  { displayName: 'Rosuvastatin', name: 'rosuvastatin' },
  { displayName: 'Salmeterol', name: 'salmeterol' },
  { displayName: 'Saquinavir', name: 'saquinavir' },
  { displayName: 'Sildenafil (pulmonary arterial hypertension use)', name: 'sildenafil' },
  { displayName: 'Simvastatin', name: 'simvastatin' },
  { displayName: 'Sirolimus', name: 'sirolimus' },
  { displayName: 'Sofosbuvir', name: 'sofosbuvir' },
  { displayName: "St. John's Wort", name: 'st_Johns_wort' },
  { displayName: 'Tacrolimus', name: 'tacrolimus' },
  { displayName: 'Tenofovir', name: 'tenofovir' },
  { displayName: 'Tipranavir', name: 'tipranavir' },
  { displayName: 'Trazodone', name: 'trazodone' },
  { displayName: 'Triamcinolone', name: 'triamcinolone' },
  { displayName: 'Triazolam', name: 'triazolam' },
  { displayName: 'Velpatasvir', name: 'velpatasvir' },
  { displayName: 'Venetoclax', name: 'venetoclax' },
  { displayName: 'Vinblastine', name: 'vinblastine' },
  { displayName: 'Vincristine', name: 'vincristine' },
  { displayName: 'Voriconazole', name: 'voriconazole' },
  { displayName: 'Voxilaprevir', name: 'voxilaprevir' },
  { displayName: 'Warfarin', name: 'warfarin' },
  { displayName: 'Zidovudine', name: 'zidovudine' },
  // { displayName: 'None of the medications listed', name: 'none_of_the_medications_listed' },
];

const RISK_FACTORS_NONE = { displayName: 'None of the above', name: 'none_of_the_above' };

const RISK_FACTORS = [
  { displayName: 'Active Cancer', name: 'active_cancer' },
  { displayName: 'Age 65 - 74', name: 'age_gte_65_lt_74' },
  { displayName: 'Age ≥ 75', name: 'age_gte_75' },
  { displayName: 'Asthma', name: 'asthma' },
  { displayName: 'COPD', name: 'copd' },
  { displayName: 'Cardiomyopathy', name: 'cardiomyopathy' },
  { displayName: 'Congestive heart failure', name: 'congestive_heart_failure' },
  { displayName: 'Coronary artery disease', name: 'coronary_artery_disease' },
  { displayName: 'Cystic fibrosis', name: 'cystic_fibrosis' },
  { displayName: 'Dementia', name: 'dementia' },
  { displayName: 'Depression, Schizophrenia, or other mood disorder', name: 'mood_disorder' },
  { displayName: 'Diabetes', name: 'diabetes' },
  { displayName: 'Down syndrome', name: 'down_syndrome' },
  { displayName: 'HIV Infection (untreated)', name: 'hiv_infection' },
  { displayName: 'High blood pressure', name: 'high_blood_pressure' },
  { displayName: 'History of stroke', name: 'history_of_stroke' },
  { displayName: 'Immune compromised', name: 'immune_compromised' },
  { displayName: 'Interstitial lung disease', name: 'interstitial_lung_disease' },
  { displayName: 'Low oxygen or needing to use an oxygen tank', name: 'low_oxygen' },
  { displayName: 'Organ or blood transplant', name: 'organ_or_blood_transplant' },
  { displayName: 'Overweight or obese (BMI > 24.9)', name: 'overweight_or_obese' },
  {
    displayName: 'Pulmonary hypertension (high blood pressure in the blood vessels of the lungs)',
    name: 'pulmonary_hypertension',
  },
  { displayName: 'Sickle cell disease or thalassemia', name: 'sickle_cell_disease_or_thalassemia' },
  { displayName: 'Smoking (past or present)', name: 'smoking' },
  { displayName: 'Substance use disorders', name: 'substance_use_disorders' },
  RISK_FACTORS_NONE,
];

const MEDICATION_NAME_MAP = {
  paxlovid: 'Paxlovid',
};

const ELIMINATION_DISEASE = [
  { displayName: 'Kidney Disease', name: 'kidney_disease' },
  { displayName: 'Liver Disease', name: 'liver_disease' },
  RISK_FACTORS_NONE,
];

export default { symptoms: SYMPTOMS, medications: MEDICATIONS, riskFactors: RISK_FACTORS };
export {
  SYMPTOM_NONE,
  SYMPTOMS,
  MEDICATIONS,
  RISK_FACTORS_NONE,
  RISK_FACTORS,
  MEDICATION_NAME_MAP,
  ELIMINATION_DISEASE,
};
